// ============================================================
// DevStash — Mock Data (temporary, until DB is wired up)
// ============================================================

export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "otunmartins@gmail.com",
  image: null,
  isPro: true,
};

export const mockItemTypes = [
  { id: "type_snippet",  name: "Snippet",  icon: "Code",       color: "#3b82f6", contentModel: "TEXT", isSystem: true },
  { id: "type_prompt",   name: "Prompt",   icon: "Sparkles",   color: "#8b5cf6", contentModel: "TEXT", isSystem: true },
  { id: "type_command",  name: "Command",  icon: "Terminal",   color: "#f97316", contentModel: "TEXT", isSystem: true },
  { id: "type_note",     name: "Note",     icon: "StickyNote", color: "#fde047", contentModel: "TEXT", isSystem: true },
  { id: "type_file",     name: "File",     icon: "File",       color: "#6b7280", contentModel: "FILE", isSystem: true },
  { id: "type_image",    name: "Image",    icon: "Image",      color: "#ec4899", contentModel: "FILE", isSystem: true },
  { id: "type_link",     name: "Link",     icon: "Link",       color: "#10b981", contentModel: "URL",  isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    createdAt: "2026-01-05T10:00:00Z",
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    createdAt: "2026-01-08T10:00:00Z",
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    createdAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    createdAt: "2026-01-12T10:00:00Z",
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    createdAt: "2026-01-14T10:00:00Z",
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    createdAt: "2026-01-15T10:00:00Z",
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    itemTypeId: "type_snippet",
    contentType: "TEXT",
    content: "export function useAuth() {\n  const session = useSession();\n  return session;\n}",
    language: "tsx",
    isFavorite: true,
    isPinned: true,
    tags: ["react", "auth", "hooks"],
    collectionIds: ["col_1"],
    createdAt: "2026-01-16T09:00:00Z",
    updatedAt: "2026-01-16T09:00:00Z",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    itemTypeId: "type_snippet",
    contentType: "TEXT",
    content: "async function fetchWithRetry(url, retries = 3) {\n  // exponential backoff logic\n}",
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    tags: ["typescript", "api", "error-handling"],
    collectionIds: ["col_1", "col_4"],
    createdAt: "2026-01-12T14:00:00Z",
    updatedAt: "2026-01-12T14:00:00Z",
  },
  {
    id: "item_3",
    title: "System Prompt — Code Reviewer",
    description: "System message for an AI code review assistant",
    itemTypeId: "type_prompt",
    contentType: "TEXT",
    content: "You are an expert code reviewer. Review the following code for bugs, performance issues, and best practices.",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "code-review"],
    collectionIds: ["col_6"],
    createdAt: "2026-01-15T11:00:00Z",
    updatedAt: "2026-01-15T11:00:00Z",
  },
  {
    id: "item_4",
    title: "Git — Undo Last Commit",
    description: "Undo the last commit while keeping changes staged",
    itemTypeId: "type_command",
    contentType: "TEXT",
    content: "git reset --soft HEAD~1",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["git"],
    collectionIds: ["col_5"],
    createdAt: "2026-01-14T08:00:00Z",
    updatedAt: "2026-01-14T08:00:00Z",
  },
  {
    id: "item_5",
    title: "Git — Interactive Rebase",
    description: "Rebase last N commits interactively",
    itemTypeId: "type_command",
    contentType: "TEXT",
    content: "git rebase -i HEAD~3",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["git"],
    collectionIds: ["col_5"],
    createdAt: "2026-01-14T08:30:00Z",
    updatedAt: "2026-01-14T08:30:00Z",
  },
  {
    id: "item_6",
    title: "Python List Comprehension Patterns",
    description: "Common list comprehension patterns with filtering",
    itemTypeId: "type_snippet",
    contentType: "TEXT",
    content: "evens = [x for x in range(20) if x % 2 == 0]",
    language: "python",
    isFavorite: false,
    isPinned: false,
    tags: ["python"],
    collectionIds: ["col_2"],
    createdAt: "2026-01-10T15:00:00Z",
    updatedAt: "2026-01-10T15:00:00Z",
  },
  {
    id: "item_7",
    title: "Project Context — DevStash",
    description: "AI context file describing the DevStash project",
    itemTypeId: "type_file",
    contentType: "FILE",
    content: null,
    fileUrl: "/files/devstash-context.md",
    fileName: "devstash-context.md",
    fileSize: 4096,
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "context"],
    collectionIds: ["col_3"],
    createdAt: "2026-01-11T09:00:00Z",
    updatedAt: "2026-01-11T09:00:00Z",
  },
  {
    id: "item_8",
    title: "Prompt Optimizer — ChatGPT",
    description: "Rewrite vague prompts into structured, effective ones",
    itemTypeId: "type_prompt",
    contentType: "TEXT",
    content: "Rewrite the following prompt to be clearer, more specific, and output-oriented:",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "prompts"],
    collectionIds: ["col_6"],
    createdAt: "2026-01-13T10:00:00Z",
    updatedAt: "2026-01-13T10:00:00Z",
  },
  {
    id: "item_9",
    title: "useLocalStorage Hook",
    description: "Syncs state with localStorage with SSR safety",
    itemTypeId: "type_snippet",
    contentType: "TEXT",
    content: "export function useLocalStorage<T>(key: string, initial: T) {\n  // implementation\n}",
    language: "tsx",
    isFavorite: false,
    isPinned: false,
    tags: ["react", "hooks"],
    collectionIds: ["col_1"],
    createdAt: "2026-01-09T11:00:00Z",
    updatedAt: "2026-01-09T11:00:00Z",
  },
  {
    id: "item_10",
    title: "Big O Cheatsheet Note",
    description: "Quick reference for common algorithm complexities",
    itemTypeId: "type_note",
    contentType: "TEXT",
    content: "| Algorithm | Time | Space |\n|---|---|---|\n| Binary Search | O(log n) | O(1) |",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["algorithms", "interview"],
    collectionIds: ["col_4"],
    createdAt: "2026-01-12T16:00:00Z",
    updatedAt: "2026-01-12T16:00:00Z",
  },
];

// Derived counts for sidebar display
export const mockTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 18,
  type_command: 15,
  type_note: 12,
  type_file: 5,
  type_image: 3,
  type_link: 6,
};
